version: "3.8"
services:
  api:
    build: ./server
    container_name: nbbroweb_api
    env_file:
      - .env
    environment:
      - PORT=4444
    volumes:
      - api_uploads:/app/uploads
      - api_data:/app/data.db
      - api_log:/app/server.log
    ports:
      - "4444:4444"
    restart: unless-stopped

  web:
    build: ./frontend
    container_name: nbbroweb_web
    depends_on:
      - api
    ports:
      - "88:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

volumes:
  api_uploads:
  api_data:
  api_log:
